[package]
name = "what-http-rust"
version = "0.1.0"
authors = ["Kent Utterback <utterback.kent.a@gmail.com>", "Dan Stockham <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "*"